package <PACKAGENAME>;

import java.rmi.Remote;
import java.rmi.RemoteException;

public interface <CLASSNAME> extends Remote {
    int exec(String dummy) throws RemoteException;
    int exec(String dummy, String dummy2) throws RemoteException;
    int exec(String dummy, String dummy2, String dummy3) throws RemoteException;
    int execute(String dummy) throws RemoteException;
    int execute(String dummy, String dummy2) throws RemoteException;
    int execute(String dummy, String dummy2, String dummy3) throws RemoteException;
    int execCmd(String dummy) throws RemoteException;
    int execCmd(String dummy, String dummy2) throws RemoteException;
    int execCmd(String dummy, String dummy2, String dummy3) throws RemoteException;
    int cmd(String dummy) throws RemoteException;
    int cmd(String dummy, String dummy2) throws RemoteException;
    int cmd(String dummy, String dummy2, String dummy3) throws RemoteException;
    int command(String dummy) throws RemoteException;
    int command(String dummy, String dummy2) throws RemoteException;
    int command(String dummy, String dummy2, String dummy3) throws RemoteException;
    int sys(String dummy) throws RemoteException;
    int sys(String dummy, String dummy2) throws RemoteException;
    int sys(String dummy, String dummy2, String dummy3) throws RemoteException;
    int system(String dummy) throws RemoteException;
    int system(String dummy, String dummy2) throws RemoteException;
    int system(String dummy, String dummy2, String dummy3) throws RemoteException;
    int os(String dummy) throws RemoteException;
    int os(String dummy, String dummy2) throws RemoteException;
    int os(String dummy, String dummy2, String dummy3) throws RemoteException;
    int call(String dummy) throws RemoteException;
    int call(String dummy, String dummy2) throws RemoteException;
    int call(String dummy, String dummy2, String dummy3) throws RemoteException;
    int sysCall(String dummy) throws RemoteException;
    int sysCall(String dummy, String dummy2) throws RemoteException;
    int sysCall(String dummy, String dummy2, String dummy3) throws RemoteException;
    int run(String dummy) throws RemoteException;
    int run(String dummy, String dummy2) throws RemoteException;
    int run(String dummy, String dummy2, String dummy3) throws RemoteException;
    int start(String dummy) throws RemoteException;
    int start(String dummy, String dummy2) throws RemoteException;
    int start(String dummy, String dummy2, String dummy3) throws RemoteException;
    int passthru(String dummy) throws RemoteException;
    int passthru(String dummy, String dummy2) throws RemoteException;
    int passthru(String dummy, String dummy2, String dummy3) throws RemoteException;
    int shellExec(String dummy) throws RemoteException;
    int shellExec(String dummy, String dummy2) throws RemoteException;
    int shellExec(String dummy, String dummy2, String dummy3) throws RemoteException;
    int login(String dummy) throws RemoteException;
    int login(String dummy, String dummy2) throws RemoteException;
    int login(String dummy, String dummy2, String dummy3) throws RemoteException;
    int loginUser(String dummy) throws RemoteException;
    int loginUser(String dummy, String dummy2) throws RemoteException;
    int loginUser(String dummy, String dummy2, String dummy3) throws RemoteException;
    int register(String dummy) throws RemoteException;
    int register(String dummy, String dummy2) throws RemoteException;
    int register(String dummy, String dummy2, String dummy3) throws RemoteException;
    int cancel(String dummy) throws RemoteException;
    int cancel(String dummy, String dummy2) throws RemoteException;
    int cancel(String dummy, String dummy2, String dummy3) throws RemoteException;
    int request(String dummy) throws RemoteException;
    int request(String dummy, String dummy2) throws RemoteException;
    int request(String dummy, String dummy2, String dummy3) throws RemoteException;
    int logout(String dummy) throws RemoteException;
    int logout(String dummy, String dummy2) throws RemoteException;
    int logout(String dummy, String dummy2, String dummy3) throws RemoteException;
    int reset(String dummy) throws RemoteException;
    int reset(String dummy, String dummy2) throws RemoteException;
    int reset(String dummy, String dummy2, String dummy3) throws RemoteException;
    int log(String dummy) throws RemoteException;
    int log(String dummy, String dummy2) throws RemoteException;
    int log(String dummy, String dummy2, String dummy3) throws RemoteException;
    int logMessage(String dummy) throws RemoteException;
    int logMessage(String dummy, String dummy2) throws RemoteException;
    int logMessage(String dummy, String dummy2, String dummy3) throws RemoteException;

    int exec(String[] dummy) throws RemoteException;
    int exec(String dummy, String[] dummy2) throws RemoteException;
    int execute(String[] dummy) throws RemoteException;
    int execute(String dummy, String[] dummy2) throws RemoteException;
    int execCmd(String[] dummy) throws RemoteException;
    int execCmd(String dummy, String[] dummy2) throws RemoteException;
    int cmd(String[] dummy) throws RemoteException;
    int cmd(String dummy, String[] dummy2) throws RemoteException;
    int command(String[] dummy) throws RemoteException;
    int command(String dummy, String[] dummy2) throws RemoteException;
    int sys(String[] dummy) throws RemoteException;
    int sys(String dummy, String[] dummy2) throws RemoteException;
    int system(String[] dummy) throws RemoteException;
    int system(String dummy, String[] dummy2) throws RemoteException;
    int os(String[] dummy) throws RemoteException;
    int os(String dummy, String[] dummy2) throws RemoteException;
    int call(String[] dummy) throws RemoteException;
    int call(String dummy, String[] dummy2) throws RemoteException;
    int sysCall(String[] dummy) throws RemoteException;
    int sysCall(String dummy, String[] dummy2) throws RemoteException;
    int run(String[] dummy) throws RemoteException;
    int run(String dummy, String[] dummy2) throws RemoteException;
    int start(String[] dummy) throws RemoteException;
    int start(String dummy, String[] dummy2) throws RemoteException;
    int passthru(String[] dummy) throws RemoteException;
    int passthru(String dummy, String[] dummy2) throws RemoteException;
    int shellExec(String[] dummy) throws RemoteException;
    int shellExec(String dummy, String[] dummy2) throws RemoteException;
    int login(String[] dummy) throws RemoteException;
    int login(String[] dummy, String dummy2) throws RemoteException;
    int login(String dummy, String[] dummy2) throws RemoteException;
    int loginUser(String[] dummy) throws RemoteException;
    int loginUser(String[] dummy, String dummy2) throws RemoteException;
    int loginUser(String dummy, String[] dummy2) throws RemoteException;
    int register(String[] dummy) throws RemoteException;
    int register(String[] dummy, String dummy2) throws RemoteException;
    int register(String dummy, String[] dummy2) throws RemoteException;
    int cancel(String[] dummy) throws RemoteException;
    int cancel(String[] dummy, String dummy2) throws RemoteException;
    int cancel(String dummy, String[] dummy2) throws RemoteException;
    int request(String[] dummy) throws RemoteException;
    int request(String[] dummy, String dummy2) throws RemoteException;
    int request(String dummy, String[] dummy2) throws RemoteException;
    int logout(String[] dummy) throws RemoteException;
    int logout(String[] dummy, String dummy2) throws RemoteException;
    int logout(String dummy, String[] dummy2) throws RemoteException;
    int reset(String[] dummy) throws RemoteException;
    int reset(String[] dummy, String dummy2) throws RemoteException;
    int reset(String dummy, String dummy2[]) throws RemoteException;

    int log(int logLevel, String message) throws RemoteException;
    int logMessage(int logLevel, String message) throws RemoteException;
    int error(int dummy1, String dummy2) throws RemoteException;
    int cancel(int dummy1, String dummy2) throws RemoteException;
    int reset(int dummy1, String dummy2) throws RemoteException;
}
