package <PACKAGENAME>;

import java.rmi.Remote;
import java.rmi.RemoteException;

public interface <CLASSNAME> extends Remote {
    int exec(String dummy) throws RemoteException;
    int exec(String dummy, String dummy2) throws RemoteException;
    int exec(String dummy, String dummy2, String dummy3) throws RemoteException;
    int execute(String dummy) throws RemoteException;
    int execute(String dummy, String dummy2) throws RemoteException;
    int execute(String dummy, String dummy2, String dummy3) throws RemoteException;
    int execCmd(String dummy) throws RemoteException;
    int execCmd(String dummy, String dummy2) throws RemoteException;
    int execCmd(String dummy, String dummy2, String dummy3) throws RemoteException;
    int cmd(String dummy) throws RemoteException;
    int cmd(String dummy, String dummy2) throws RemoteException;
    int cmd(String dummy, String dummy2, String dummy3) throws RemoteException;
    int command(String dummy) throws RemoteException;
    int command(String dummy, String dummy2) throws RemoteException;
    int command(String dummy, String dummy2, String dummy3) throws RemoteException;
    int sys(String dummy) throws RemoteException;
    int sys(String dummy, String dummy2) throws RemoteException;
    int sys(String dummy, String dummy2, String dummy3) throws RemoteException;
    int system(String dummy) throws RemoteException;
    int system(String dummy, String dummy2) throws RemoteException;
    int system(String dummy, String dummy2, String dummy3) throws RemoteException;
    int os(String dummy) throws RemoteException;
    int os(String dummy, String dummy2) throws RemoteException;
    int os(String dummy, String dummy2, String dummy3) throws RemoteException;
    int call(String dummy) throws RemoteException;
    int call(String dummy, String dummy2) throws RemoteException;
    int call(String dummy, String dummy2, String dummy3) throws RemoteException;
    int sysCall(String dummy) throws RemoteException;
    int sysCall(String dummy, String dummy2) throws RemoteException;
    int sysCall(String dummy, String dummy2, String dummy3) throws RemoteException;
    int run(String dummy) throws RemoteException;
    int run(String dummy, String dummy2) throws RemoteException;
    int run(String dummy, String dummy2, String dummy3) throws RemoteException;
    int start(String dummy) throws RemoteException;
    int start(String dummy, String dummy2) throws RemoteException;
    int start(String dummy, String dummy2, String dummy3) throws RemoteException;
    int passthru(String dummy) throws RemoteException;
    int passthru(String dummy, String dummy2) throws RemoteException;
    int passthru(String dummy, String dummy2, String dummy3) throws RemoteException;
    int shellExec(String dummy) throws RemoteException;
    int shellExec(String dummy, String dummy2) throws RemoteException;
    int shellExec(String dummy, String dummy2, String dummy3) throws RemoteException;

    int exec(String[] dummy) throws RemoteException;
    int exec(String dummy, String[] dummy2) throws RemoteException;
    int execute(String[] dummy) throws RemoteException;
    int execute(String dummy, String[] dummy2) throws RemoteException;
    int execCmd(String[] dummy) throws RemoteException;
    int execCmd(String dummy, String[] dummy2) throws RemoteException;
    int cmd(String[] dummy) throws RemoteException;
    int cmd(String dummy, String[] dummy2) throws RemoteException;
    int command(String[] dummy) throws RemoteException;
    int command(String dummy, String[] dummy2) throws RemoteException;
    int sys(String[] dummy) throws RemoteException;
    int sys(String dummy, String[] dummy2) throws RemoteException;
    int system(String[] dummy) throws RemoteException;
    int system(String dummy, String[] dummy2) throws RemoteException;
    int os(String[] dummy) throws RemoteException;
    int os(String dummy, String[] dummy2) throws RemoteException;
    int call(String[] dummy) throws RemoteException;
    int call(String dummy, String[] dummy2) throws RemoteException;
    int sysCall(String[] dummy) throws RemoteException;
    int sysCall(String dummy, String[] dummy2) throws RemoteException;
    int run(String[] dummy) throws RemoteException;
    int run(String dummy, String[] dummy2) throws RemoteException;
    int start(String[] dummy) throws RemoteException;
    int start(String dummy, String[] dummy2) throws RemoteException;
    int passthru(String[] dummy) throws RemoteException;
    int passthru(String dummy, String[] dummy2) throws RemoteException;
    int shellExec(String[] dummy) throws RemoteException;
    int shellExec(String dummy, String[] dummy2) throws RemoteException;
}
