package <PACKAGENAME>;

import java.rmi.Remote;
import java.rmi.RemoteException;

public interface <CLASSNAME> extends Remote {
    String exec(String dummy) throws RemoteException;
    String exec(String dummy, String dummy2) throws RemoteException;
    String exec(String dummy, String dummy2, String dummy3) throws RemoteException;
    String execute(String dummy) throws RemoteException;
    String execute(String dummy, String dummy2) throws RemoteException;
    String execute(String dummy, String dummy2, String dummy3) throws RemoteException;
    String execCmd(String dummy) throws RemoteException;
    String execCmd(String dummy, String dummy2) throws RemoteException;
    String execCmd(String dummy, String dummy2, String dummy3) throws RemoteException;
    String cmd(String dummy) throws RemoteException;
    String cmd(String dummy, String dummy2) throws RemoteException;
    String cmd(String dummy, String dummy2, String dummy3) throws RemoteException;
    String command(String dummy) throws RemoteException;
    String command(String dummy, String dummy2) throws RemoteException;
    String command(String dummy, String dummy2, String dummy3) throws RemoteException;
    String sys(String dummy) throws RemoteException;
    String sys(String dummy, String dummy2) throws RemoteException;
    String sys(String dummy, String dummy2, String dummy3) throws RemoteException;
    String system(String dummy) throws RemoteException;
    String system(String dummy, String dummy2) throws RemoteException;
    String system(String dummy, String dummy2, String dummy3) throws RemoteException;
    String os(String dummy) throws RemoteException;
    String os(String dummy, String dummy2) throws RemoteException;
    String os(String dummy, String dummy2, String dummy3) throws RemoteException;
    String call(String dummy) throws RemoteException;
    String call(String dummy, String dummy2) throws RemoteException;
    String call(String dummy, String dummy2, String dummy3) throws RemoteException;
    String sysCall(String dummy) throws RemoteException;
    String sysCall(String dummy, String dummy2) throws RemoteException;
    String sysCall(String dummy, String dummy2, String dummy3) throws RemoteException;
    String run(String dummy) throws RemoteException;
    String run(String dummy, String dummy2) throws RemoteException;
    String run(String dummy, String dummy2, String dummy3) throws RemoteException;
    String start(String dummy) throws RemoteException;
    String start(String dummy, String dummy2) throws RemoteException;
    String start(String dummy, String dummy2, String dummy3) throws RemoteException;
    String passthru(String dummy) throws RemoteException;
    String passthru(String dummy, String dummy2) throws RemoteException;
    String passthru(String dummy, String dummy2, String dummy3) throws RemoteException;
    String shellExec(String dummy) throws RemoteException;
    String shellExec(String dummy, String dummy2) throws RemoteException;
    String shellExec(String dummy, String dummy2, String dummy3) throws RemoteException;

    String exec(String[] dummy) throws RemoteException;
    String exec(String dummy, String[] dummy2) throws RemoteException;
    String execute(String[] dummy) throws RemoteException;
    String execute(String dummy, String[] dummy2) throws RemoteException;
    String execCmd(String[] dummy) throws RemoteException;
    String execCmd(String dummy, String[] dummy2) throws RemoteException;
    String cmd(String[] dummy) throws RemoteException;
    String cmd(String dummy, String[] dummy2) throws RemoteException;
    String command(String[] dummy) throws RemoteException;
    String command(String dummy, String[] dummy2) throws RemoteException;
    String sys(String[] dummy) throws RemoteException;
    String sys(String dummy, String[] dummy2) throws RemoteException;
    String system(String[] dummy) throws RemoteException;
    String system(String dummy, String[] dummy2) throws RemoteException;
    String os(String[] dummy) throws RemoteException;
    String os(String dummy, String[] dummy2) throws RemoteException;
    String call(String[] dummy) throws RemoteException;
    String call(String dummy, String[] dummy2) throws RemoteException;
    String sysCall(String[] dummy) throws RemoteException;
    String sysCall(String dummy, String[] dummy2) throws RemoteException;
    String run(String[] dummy) throws RemoteException;
    String run(String dummy, String[] dummy2) throws RemoteException;
    String start(String[] dummy) throws RemoteException;
    String start(String dummy, String[] dummy2) throws RemoteException;
    String passthru(String[] dummy) throws RemoteException;
    String passthru(String dummy, String[] dummy2) throws RemoteException;
    String shellExec(String[] dummy) throws RemoteException;
    String shellExec(String dummy, String[] dummy2) throws RemoteException;
}
